<div class="container-fluid px-4 py-3">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-primary text-white">
                    <div class="d-flex justify-content-between align-items-center flex-wrap">
                        <h5 class="mb-0 fw-bold"><i class="fas fa-plus-circle me-2"></i>Create New Student</h5>
                        <div class="d-flex gap-2 mt-2 mt-md-0">
                            <button type="button" class="btn btn-light btn-sm" data-bs-toggle="collapse" data-bs-target="#excelImportSection">
                                <i class="fas fa-file-excel me-1"></i>Import from Excel
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <?php if (isset($error)): ?>
                        <div class="alert alert-danger alert-dismissible fade show d-flex align-items-start" role="alert">
                            <i class="fas fa-exclamation-circle me-2 mt-1"></i>
                            <div><?php 
                                // Errors from controller may contain HTML (like <br> tags) for formatting
                                // These are safe since they're generated by the controller, not user input
                                echo $error; 
                            ?></div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>
                    <?php endif; ?>
                    
                    <?php if (isset($message)): ?>
                        <div class="alert alert-success alert-dismissible fade show d-flex align-items-start" role="alert">
                            <i class="fas fa-check-circle me-2 mt-1"></i>
                            <div><?php 
                                // Messages from controller may contain HTML (like <br> tags) for formatting
                                // These are safe since they're generated by the controller, not user input
                                echo $message; 
                            ?></div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>
                    <?php endif; ?>
                    
                    <!-- Excel Import Section -->
                    <div class="collapse mb-4" id="excelImportSection">
                        <div class="card border border-info">
                            <div class="card-header bg-info bg-opacity-10">
                                <h6 class="mb-0 fw-bold text-info">
                                    <i class="fas fa-file-excel me-2"></i>Import Students from Excel/CSV
                                </h6>
                            </div>
                            <div class="card-body">
                                <div class="alert alert-info d-flex align-items-start">
                                    <i class="fas fa-info-circle me-2 mt-1"></i>
                                    <div>
                                        <strong>Instructions:</strong>
                                        <ul class="mb-0 mt-2">
                                            <li>Excel/CSV file must contain columns: <strong>student_id</strong>, <strong>fullname</strong>, <strong>NIC</strong></li>
                                            <li>Select Department, Course, Academic Year, Course Mode, and Enrollment Status below</li>
                                            <li>All imported students will be enrolled with the selected values</li>
                                            <li>Enrollment Status will be set to "Following" by default</li>
                                            <li><strong>Note:</strong> For Excel files (.xlsx/.xls), please save as CSV format first (File > Save As > CSV)</li>
                                            <li>Download sample file: <a href="<?php echo APP_URL; ?>/students/download-sample-excel" target="_blank" class="alert-link fw-bold"><i class="fas fa-download me-1"></i>Download Sample CSV File</a></li>
                                        </ul>
                                    </div>
                                </div>
                                
                                <form method="POST" action="<?php echo APP_URL; ?>/students/import-excel" enctype="multipart/form-data" id="excelImportForm">
                                    <div class="row g-3">
                                        <div class="col-md-6">
                                            <label for="import_department_id" class="form-label fw-semibold">Department <span class="text-danger">*</span></label>
                                            <select class="form-select" id="import_department_id" name="department_id" required>
                                                <option value="">Select Department</option>
                                                <?php if (isset($departments) && !empty($departments)): ?>
                                                    <?php foreach ($departments as $department): ?>
                                                        <option value="<?php echo htmlspecialchars($department['department_id']); ?>">
                                                            <?php echo htmlspecialchars($department['department_name']); ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>
                                        </div>
                                        
                                        <div class="col-md-6">
                                            <label for="import_course_id" class="form-label fw-semibold">Course <span class="text-danger">*</span></label>
                                            <select class="form-select" id="import_course_id" name="course_id" required disabled>
                                                <option value="">Select Department First</option>
                                                <?php if (isset($courses) && !empty($courses)): ?>
                                                    <?php foreach ($courses as $course): ?>
                                                        <option value="<?php echo htmlspecialchars($course['course_id']); ?>" 
                                                                data-department-id="<?php echo htmlspecialchars($course['department_id'] ?? ''); ?>">
                                                            <?php echo htmlspecialchars($course['course_name']); ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="row g-3 mt-2">
                                        <div class="col-md-4">
                                            <label for="import_academic_year" class="form-label fw-semibold">Academic Year <span class="text-danger">*</span></label>
                                            <select class="form-select" id="import_academic_year" name="academic_year" required>
                                                <option value="">Select Academic Year</option>
                                                <?php if (isset($academicYears) && !empty($academicYears)): ?>
                                                    <?php foreach ($academicYears as $year): ?>
                                                        <option value="<?php echo htmlspecialchars($year); ?>">
                                                            <?php echo htmlspecialchars($year); ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>
                                        </div>
                                        
                                        <div class="col-md-4">
                                            <label for="import_course_mode" class="form-label fw-semibold">Course Mode</label>
                                            <select class="form-select" id="import_course_mode" name="course_mode">
                                                <option value="Full Time" selected>Full Time</option>
                                                <option value="Part Time">Part Time</option>
                                            </select>
                                        </div>
                                        
                                        <div class="col-md-4">
                                            <label for="import_enroll_status" class="form-label fw-semibold">Enrollment Status</label>
                                            <select class="form-select" id="import_enroll_status" name="student_enroll_status">
                                                <option value="Following" selected>Following</option>
                                                <option value="Dropout">Dropout</option>
                                                <option value="Completed">Completed</option>
                                                <option value="Long Absent">Long Absent</option>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="row g-3 mt-2">
                                        <div class="col-12">
                                            <label for="excel_file" class="form-label fw-semibold">Excel/CSV File <span class="text-danger">*</span></label>
                                            <input type="file" class="form-control" id="excel_file" name="excel_file" accept=".xlsx,.xls,.csv" required>
                                            <div class="form-text">
                                                Accepted formats: .csv (recommended), .xlsx, .xls<br>
                                                <small class="text-muted">Note: Excel files (.xlsx/.xls) need to be saved as CSV format. The sample file is in CSV format.</small>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="d-flex gap-2 mt-4">
                                        <button type="submit" class="btn btn-success">
                                            <i class="fas fa-upload me-1"></i>Import Students
                                        </button>
                                        <button type="button" class="btn btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#excelImportSection">
                                            <i class="fas fa-times me-1"></i>Cancel
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    
                    <hr class="my-4">
                    
                    <form method="POST" action="<?php echo APP_URL; ?>/students/create" id="createStudentForm">
                        <h6 class="fw-bold mb-3"><i class="fas fa-graduation-cap me-2"></i>Enrollment Information</h6>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="department_id" class="form-label fw-semibold">Department <span class="text-danger">*</span></label>
                                <select class="form-select" id="department_id" name="department_id" required>
                                    <option value="">Select Department</option>
                                    <?php if (isset($departments) && !empty($departments)): ?>
                                        <?php foreach ($departments as $department): ?>
                                            <option value="<?php echo htmlspecialchars($department['department_id']); ?>">
                                                <?php echo htmlspecialchars($department['department_name']); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="academic_year" class="form-label fw-semibold">Academic Year <span class="text-danger">*</span></label>
                                <select class="form-select" id="academic_year" name="academic_year" required>
                                    <option value="">Select Academic Year</option>
                                    <?php if (isset($academicYears) && !empty($academicYears)): ?>
                                        <?php foreach ($academicYears as $year): ?>
                                            <option value="<?php echo htmlspecialchars($year); ?>">
                                                <?php echo htmlspecialchars($year); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="course_id" class="form-label fw-semibold">Course <span class="text-danger">*</span></label>
                                <select class="form-select" id="course_id" name="course_id" required disabled>
                                    <option value="">Select Department First</option>
                                    <?php if (isset($courses) && !empty($courses)): ?>
                                        <?php 
                                        // Debug: Log first course structure (remove after debugging)
                                        if (count($courses) > 0) {
                                            error_log("First course structure: " . print_r(array_keys($courses[0]), true));
                                        }
                                        ?>
                                        <?php foreach ($courses as $course): ?>
                                            <?php 
                                            // Handle case-sensitive column names - try multiple variations
                                            $courseId = '';
                                            $departmentId = '';
                                            $courseCode = '';
                                            $courseName = '';
                                            
                                            // Try lowercase first (most common)
                                            if (isset($course['course_id'])) $courseId = $course['course_id'];
                                            elseif (isset($course['COURSE_ID'])) $courseId = $course['COURSE_ID'];
                                            elseif (isset($course['Course_ID'])) $courseId = $course['Course_ID'];
                                            
                                            if (isset($course['department_id'])) $departmentId = $course['department_id'];
                                            elseif (isset($course['DEPARTMENT_ID'])) $departmentId = $course['DEPARTMENT_ID'];
                                            elseif (isset($course['Department_ID'])) $departmentId = $course['Department_ID'];
                                            
                                            if (isset($course['course_code'])) $courseCode = $course['course_code'];
                                            elseif (isset($course['COURSE_CODE'])) $courseCode = $course['COURSE_CODE'];
                                            elseif (isset($course['Course_Code'])) $courseCode = $course['Course_Code'];
                                            
                                            if (isset($course['course_name'])) $courseName = $course['course_name'];
                                            elseif (isset($course['COURSE_NAME'])) $courseName = $course['COURSE_NAME'];
                                            elseif (isset($course['Course_Name'])) $courseName = $course['Course_Name'];
                                            
                                            // Skip if essential data is missing
                                            if (empty($courseId)) continue;
                                            ?>
                                            <option value="<?php echo htmlspecialchars($courseId); ?>" 
                                                    data-department-id="<?php echo htmlspecialchars($departmentId); ?>"
                                                    data-course-code="<?php echo htmlspecialchars($courseCode); ?>">
                                                <?php echo htmlspecialchars($courseName ?: $courseId); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <!-- Debug: No courses found -->
                                        <option value="">No courses available</option>
                                    <?php endif; ?>
                                </select>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_id" class="form-label fw-semibold">
                                    Registration Number (Student ID) <span class="text-danger">*</span>
                                </label>
                                <input type="text" class="form-control" id="student_id" name="student_id" 
                                       maxlength="50" required>
                                
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label for="course_mode" class="form-label fw-semibold">Course Mode</label>
                                <select class="form-select" id="course_mode" name="course_mode">
                                    <option value="Full Time" selected>Full Time</option>
                                    <option value="Part Time">Part Time</option>
                                </select>
                            </div>
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_enroll_status" class="form-label fw-semibold">Enrollment Status</label>
                                <select class="form-select" id="student_enroll_status" name="student_enroll_status">
                                    <option value="Following" selected>Following</option>
                                    <option value="Dropout">Dropout</option>
                                    <option value="Completed">Completed</option>
                                    <option value="Long Absent">Long Absent</option>
                                </select>
                            </div>
                        </div>
                        
                        <hr class="my-4">
                        <h6 class="fw-bold mb-3">Personal Information</h6>
                        
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label for="student_title" class="form-label fw-semibold">Title</label>
                                <select class="form-select" id="student_title" name="student_title">
                                    <option value="">Select</option>
                                    <option value="Mr.">Mr.</option>
                                    <option value="Mrs.">Mrs.</option>
                                    <option value="Miss">Miss</option>
                                </select>
                            </div>
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_gender" class="form-label fw-semibold">Gender</label>
                                <select class="form-select" id="student_gender" name="student_gender">
                                    <option value="">Select</option>
                                    <option value="Male">Male</option>
                                    <option value="Female">Female</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="student_fullname" class="form-label fw-semibold">
                                    Full Name <span class="text-danger">*</span>
                                </label>
                                <input type="text" class="form-control" id="student_fullname" name="student_fullname" 
                                       maxlength="255" required>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_nic" class="form-label fw-semibold">
                                    NIC <span class="text-danger">*</span>
                                </label>
                                <input type="text" class="form-control" id="student_nic" name="student_nic" 
                                       maxlength="12" required>
                            </div>
                        </div>
                        
                        <div class="d-flex gap-2 mt-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save me-1"></i>Create Student
                            </button>
                            <a href="<?php echo APP_URL; ?>/students" class="btn btn-outline-secondary">
                                <i class="fas fa-times me-1"></i>Cancel
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
// Complete rewrite: Handle department selection -> load courses -> generate student ID
document.addEventListener('DOMContentLoaded', function() {
    console.log('=== Student Create Form Initialized ===');
    
    // Get form elements
    const departmentSelect = document.getElementById('department_id');
    const courseSelect = document.getElementById('course_id');
    const academicYearSelect = document.getElementById('academic_year');
    const courseModeSelect = document.getElementById('course_mode');
    const studentIdInput = document.getElementById('student_id');
    const createForm = document.getElementById('createStudentForm');
    
    // Validate elements exist
    if (!departmentSelect || !courseSelect || !academicYearSelect || !studentIdInput) {
        console.error('Required form elements not found!', {
            departmentSelect: !!departmentSelect,
            courseSelect: !!courseSelect,
            academicYearSelect: !!academicYearSelect,
            studentIdInput: !!studentIdInput
        });
        return;
    }
    
    // Step 1: Store all course options from HTML on page load
    const allCourseOptions = [];
    const wasCourseDisabled = courseSelect.disabled;
    courseSelect.disabled = false; // Temporarily enable to read options
    
    for (let i = 0; i < courseSelect.options.length; i++) {
        const option = courseSelect.options[i];
        if (option.value) { // Only store actual course options, skip placeholders
            const deptId = option.getAttribute('data-department-id') || '';
            const courseCode = option.getAttribute('data-course-code') || '';
            
            // Store course data
            allCourseOptions.push({
                value: option.value,
                text: option.textContent.trim(),
                departmentId: deptId,
                courseCode: courseCode
            });
        }
    }
    
    courseSelect.disabled = wasCourseDisabled; // Restore disabled state
    console.log('✓ Stored', allCourseOptions.length, 'course options');
    
    // Step 2: Function to load courses when department is selected
    function loadCoursesForDepartment() {
        const selectedDeptId = departmentSelect.value.trim();
        
        console.log('--- Loading courses for department:', selectedDeptId, '---');
        
        // Clear course dropdown and student ID
        courseSelect.innerHTML = '<option value="">Select Course</option>';
        if (studentIdInput) {
            studentIdInput.value = '';
        }
        
        // If no department selected, disable course dropdown
        if (!selectedDeptId) {
            courseSelect.disabled = true;
            courseSelect.innerHTML = '<option value="">Select Department First</option>';
            return;
        }
        
        // Filter and add courses matching the selected department
        let matchedCount = 0;
        allCourseOptions.forEach(function(course) {
            if (course.departmentId === selectedDeptId) {
                const option = document.createElement('option');
                option.value = course.value;
                option.textContent = course.text;
                option.setAttribute('data-department-id', course.departmentId);
                option.setAttribute('data-course-code', course.courseCode);
                courseSelect.appendChild(option);
                matchedCount++;
            }
        });
        
        // Enable course dropdown if courses found
        if (matchedCount > 0) {
            courseSelect.disabled = false;
            console.log('✓ Loaded', matchedCount, 'courses for department', selectedDeptId);
        } else {
            courseSelect.disabled = true;
            courseSelect.innerHTML = '<option value="">No courses available for this department</option>';
            console.warn('✗ No courses found for department:', selectedDeptId);
        }
    }
    
    // Step 3: Function to generate student ID when course and academic year are selected
    function generateStudentId() {
        const courseId = courseSelect.value.trim();
        const academicYear = academicYearSelect.value.trim();
        const courseMode = courseModeSelect ? courseModeSelect.value : 'Full Time';
        
        console.log('--- Generating Student ID ---');
        console.log('Course:', courseId);
        console.log('Academic Year:', academicYear);
        console.log('Course Mode:', courseMode);
        
        // Clear student ID if course or academic year is missing
        if (!courseId || !academicYear) {
            if (studentIdInput) {
                studentIdInput.value = '';
            }
            console.log('Missing course or academic year');
            return;
        }
        
        // Show loading state
        if (studentIdInput) {
            studentIdInput.value = 'Loading...';
        }
        
        // Fetch last student ID via AJAX
        const url = '<?php echo APP_URL; ?>/students/get-last-reg-number?course_id=' + 
                    encodeURIComponent(courseId) + 
                    '&academic_year=' + encodeURIComponent(academicYear) + 
                    '&course_mode=' + encodeURIComponent(courseMode);
        
        console.log('Fetching from:', url);
        
        fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error('HTTP ' + response.status);
                }
                return response.json();
            })
            .then(data => {
                console.log('Server response:', data);
                
                if (data.success && data.lastRegNumber && studentIdInput) {
                    // Backend now returns the next available ID that doesn't exist yet
                    const nextAvailableId = data.lastRegNumber;
                    console.log('Next Available Student ID:', nextAvailableId);
                    
                    // Use the ID directly (backend already found the next available one)
                    studentIdInput.value = nextAvailableId;
                    console.log('✓ Generated Student ID:', nextAvailableId);
                } else {
                    if (studentIdInput) {
                        studentIdInput.value = '';
                    }
                    console.log('No student ID found:', data.error || 'Unknown error');
                }
            })
            .catch(error => {
                console.error('Error:', error);
                if (studentIdInput) {
                    studentIdInput.value = '';
                }
            });
    }
    
    // Step 4: Set up event listeners
    
    // Department change: Load courses
    departmentSelect.addEventListener('change', function() {
        console.log('Department changed to:', this.value);
        loadCoursesForDepartment();
        // Clear course and student ID
        courseSelect.value = '';
        if (studentIdInput) {
            studentIdInput.value = '';
        }
    });
    
    // Course change: Generate student ID (if academic year is also selected)
    courseSelect.addEventListener('change', function() {
        console.log('Course changed to:', this.value);
        if (academicYearSelect.value) {
            generateStudentId();
        } else {
            if (studentIdInput) {
                studentIdInput.value = '';
            }
        }
    });
    
    // Academic Year change: Generate student ID (if course is also selected)
    academicYearSelect.addEventListener('change', function() {
        console.log('Academic Year changed to:', this.value);
        if (courseSelect.value) {
            generateStudentId();
        } else {
            if (studentIdInput) {
                studentIdInput.value = '';
            }
        }
    });
    
    // Course Mode change: Regenerate student ID (if course and academic year are selected)
    if (courseModeSelect) {
        courseModeSelect.addEventListener('change', function() {
            console.log('Course Mode changed to:', this.value);
            if (courseSelect.value && academicYearSelect.value) {
                generateStudentId();
            }
        });
    }
    
    // Also use form-level event delegation as backup
    if (createForm) {
        createForm.addEventListener('change', function(e) {
            if (e.target.id === 'department_id') {
                loadCoursesForDepartment();
            } else if (e.target.id === 'course_id' || e.target.id === 'academic_year' || e.target.id === 'course_mode') {
                if (courseSelect.value && academicYearSelect.value) {
                    generateStudentId();
                }
            }
        });
    }
    
    // If department is pre-selected on page load, load courses
    if (departmentSelect.value) {
        console.log('Department pre-selected:', departmentSelect.value);
        loadCoursesForDepartment();
    }
    
    console.log('=== Form initialization complete ===');
});

// Excel Import Form - Department and Course filtering (separate from create form)
document.addEventListener('DOMContentLoaded', function() {
    const importDepartmentSelect = document.getElementById('import_department_id');
    const importCourseSelect = document.getElementById('import_course_id');
    const allImportCourseOptions = [];
    
    if (importCourseSelect) {
        for (let i = 0; i < importCourseSelect.options.length; i++) {
            allImportCourseOptions.push(importCourseSelect.options[i]);
        }
    }
    
    function filterImportCoursesByDepartment() {
        const selectedDepartmentId = importDepartmentSelect ? importDepartmentSelect.value : '';
        
        if (!importCourseSelect) return;
        
        // Clear current options
        importCourseSelect.innerHTML = '<option value="">Select Course</option>';
        
        if (!selectedDepartmentId) {
            importCourseSelect.disabled = true;
            importCourseSelect.innerHTML = '<option value="">Select Department First</option>';
            return;
        }
        
        // Add courses that match the selected department
        let hasCourses = false;
        allImportCourseOptions.forEach(function(option) {
            if (option.value && option.getAttribute('data-department-id') === selectedDepartmentId) {
                importCourseSelect.appendChild(option.cloneNode(true));
                hasCourses = true;
            }
        });
        
        if (hasCourses) {
            importCourseSelect.disabled = false;
        } else {
            importCourseSelect.disabled = true;
            importCourseSelect.innerHTML = '<option value="">No courses available for this department</option>';
        }
    }
    
    if (importDepartmentSelect) {
        importDepartmentSelect.addEventListener('change', filterImportCoursesByDepartment);
    }
    
    // Form validation: Ensure Student ID, Full Name, and NIC are required
    const createForm = document.getElementById('createStudentForm');
    const studentIdInput = document.getElementById('student_id');
    const fullNameInput = document.getElementById('student_fullname');
    const nicInput = document.getElementById('student_nic');
    
    if (createForm && studentIdInput && fullNameInput && nicInput) {
        createForm.addEventListener('submit', function(e) {
            // Validate Student ID
            if (!studentIdInput.value.trim()) {
                e.preventDefault();
                alert('Student ID is required.');
                studentIdInput.focus();
                return false;
            }
            
            // Validate Full Name
            if (!fullNameInput.value.trim()) {
                e.preventDefault();
                alert('Full Name is required.');
                fullNameInput.focus();
                return false;
            }
            
            // Validate NIC
            if (!nicInput.value.trim()) {
                e.preventDefault();
                alert('NIC is required.');
                nicInput.focus();
                return false;
            }
        });
    }
});
</script>

