<div class="container-fluid px-4 py-3">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-primary text-white">
                    <div class="d-flex justify-content-between align-items-center flex-wrap">
                        <h5 class="mb-0 fw-bold"><i class="fas fa-plus-circle me-2"></i>Create New Student</h5>
                        <div class="d-flex gap-2 mt-2 mt-md-0">
                            <button type="button" class="btn btn-light btn-sm" data-bs-toggle="collapse" data-bs-target="#excelImportSection">
                                <i class="fas fa-file-excel me-1"></i>Import from Excel
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <?php if (isset($error)): ?>
                        <div class="alert alert-danger alert-dismissible fade show d-flex align-items-start" role="alert">
                            <i class="fas fa-exclamation-circle me-2 mt-1"></i>
                            <div><?php 
                                // Errors from controller may contain HTML (like <br> tags) for formatting
                                // These are safe since they're generated by the controller, not user input
                                echo $error; 
                            ?></div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>
                    <?php endif; ?>
                    
                    <?php if (isset($message)): ?>
                        <div class="alert alert-success alert-dismissible fade show d-flex align-items-start" role="alert">
                            <i class="fas fa-check-circle me-2 mt-1"></i>
                            <div><?php 
                                // Messages from controller may contain HTML (like <br> tags) for formatting
                                // These are safe since they're generated by the controller, not user input
                                echo $message; 
                            ?></div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                        </div>
                    <?php endif; ?>
                    
                    <!-- Excel Import Section -->
                    <div class="collapse mb-4" id="excelImportSection">
                        <div class="card border border-info">
                            <div class="card-header bg-info bg-opacity-10">
                                <h6 class="mb-0 fw-bold text-info">
                                    <i class="fas fa-file-excel me-2"></i>Import Students from Excel/CSV
                                </h6>
                            </div>
                            <div class="card-body">
                                <div class="alert alert-info d-flex align-items-start">
                                    <i class="fas fa-info-circle me-2 mt-1"></i>
                                    <div>
                                        <strong>Instructions:</strong>
                                        <ul class="mb-0 mt-2">
                                            <li>Excel/CSV file must contain columns: <strong>student_id</strong>, <strong>fullname</strong>, <strong>NIC</strong></li>
                                            <li>Select Department, Course, Academic Year, Course Mode, and Enrollment Status below</li>
                                            <li>All imported students will be enrolled with the selected values</li>
                                            <li>Enrollment Status will be set to "Following" by default</li>
                                            <li><strong>Note:</strong> For Excel files (.xlsx/.xls), please save as CSV format first (File > Save As > CSV)</li>
                                            <li>Download sample file: <a href="<?php echo APP_URL; ?>/students/download-sample-excel" target="_blank" class="alert-link fw-bold"><i class="fas fa-download me-1"></i>Download Sample CSV File</a></li>
                                        </ul>
                                    </div>
                                </div>
                                
                                <form method="POST" action="<?php echo APP_URL; ?>/students/import-excel" enctype="multipart/form-data" id="excelImportForm">
                                    <div class="row g-3">
                                        <div class="col-md-6">
                                            <label for="import_department_id" class="form-label fw-semibold">Department <span class="text-danger">*</span></label>
                                            <select class="form-select" id="import_department_id" name="department_id" required>
                                                <option value="">Select Department</option>
                                                <?php if (isset($departments) && !empty($departments)): ?>
                                                    <?php foreach ($departments as $department): ?>
                                                        <option value="<?php echo htmlspecialchars($department['department_id']); ?>">
                                                            <?php echo htmlspecialchars($department['department_name']); ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>
                                        </div>
                                        
                                        <div class="col-md-6">
                                            <label for="import_course_id" class="form-label fw-semibold">Course <span class="text-danger">*</span></label>
                                            <select class="form-select" id="import_course_id" name="course_id" required disabled>
                                                <option value="">Select Department First</option>
                                                <?php if (isset($courses) && !empty($courses)): ?>
                                                    <?php foreach ($courses as $course): ?>
                                                        <option value="<?php echo htmlspecialchars($course['course_id']); ?>" 
                                                                data-department-id="<?php echo htmlspecialchars($course['department_id'] ?? ''); ?>">
                                                            <?php echo htmlspecialchars($course['course_name']); ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="row g-3 mt-2">
                                        <div class="col-md-4">
                                            <label for="import_academic_year" class="form-label fw-semibold">Academic Year <span class="text-danger">*</span></label>
                                            <select class="form-select" id="import_academic_year" name="academic_year" required>
                                                <option value="">Select Academic Year</option>
                                                <?php if (isset($academicYears) && !empty($academicYears)): ?>
                                                    <?php foreach ($academicYears as $year): ?>
                                                        <option value="<?php echo htmlspecialchars($year); ?>">
                                                            <?php echo htmlspecialchars($year); ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                            </select>
                                        </div>
                                        
                                        <div class="col-md-4">
                                            <label for="import_course_mode" class="form-label fw-semibold">Course Mode</label>
                                            <select class="form-select" id="import_course_mode" name="course_mode">
                                                <option value="Full Time" selected>Full Time</option>
                                                <option value="Part Time">Part Time</option>
                                            </select>
                                        </div>
                                        
                                        <div class="col-md-4">
                                            <label for="import_enroll_status" class="form-label fw-semibold">Enrollment Status</label>
                                            <select class="form-select" id="import_enroll_status" name="student_enroll_status">
                                                <option value="Following" selected>Following</option>
                                                <option value="Dropout">Dropout</option>
                                                <option value="Completed">Completed</option>
                                                <option value="Long Absent">Long Absent</option>
                                            </select>
                                        </div>
                                    </div>
                                    
                                    <div class="row g-3 mt-2">
                                        <div class="col-12">
                                            <label for="excel_file" class="form-label fw-semibold">Excel/CSV File <span class="text-danger">*</span></label>
                                            <input type="file" class="form-control" id="excel_file" name="excel_file" accept=".xlsx,.xls,.csv" required>
                                            <div class="form-text">
                                                Accepted formats: .csv (recommended), .xlsx, .xls<br>
                                                <small class="text-muted">Note: Excel files (.xlsx/.xls) need to be saved as CSV format. The sample file is in CSV format.</small>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="d-flex gap-2 mt-4">
                                        <button type="submit" class="btn btn-success">
                                            <i class="fas fa-upload me-1"></i>Import Students
                                        </button>
                                        <button type="button" class="btn btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#excelImportSection">
                                            <i class="fas fa-times me-1"></i>Cancel
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    
                    <hr class="my-4">
                    
                    <form method="POST" action="<?php echo APP_URL; ?>/students/create" id="createStudentForm">
                        <h6 class="fw-bold mb-3"><i class="fas fa-graduation-cap me-2"></i>Enrollment Information</h6>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="department_id" class="form-label fw-semibold">Department <span class="text-danger">*</span></label>
                                <select class="form-select" id="department_id" name="department_id" required>
                                    <option value="">Select Department</option>
                                    <?php if (isset($departments) && !empty($departments)): ?>
                                        <?php foreach ($departments as $department): ?>
                                            <option value="<?php echo htmlspecialchars($department['department_id']); ?>">
                                                <?php echo htmlspecialchars($department['department_name']); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="academic_year" class="form-label fw-semibold">Academic Year <span class="text-danger">*</span></label>
                                <select class="form-select" id="academic_year" name="academic_year" required>
                                    <option value="">Select Academic Year</option>
                                    <?php if (isset($academicYears) && !empty($academicYears)): ?>
                                        <?php foreach ($academicYears as $year): ?>
                                            <option value="<?php echo htmlspecialchars($year); ?>">
                                                <?php echo htmlspecialchars($year); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="course_id" class="form-label fw-semibold">Course <span class="text-danger">*</span></label>
                                <select class="form-select" id="course_id" name="course_id" required disabled>
                                    <option value="">Select Department First</option>
                                    <?php if (isset($courses) && !empty($courses)): ?>
                                        <?php foreach ($courses as $course): ?>
                                            <option value="<?php echo htmlspecialchars($course['course_id']); ?>" 
                                                    data-department-id="<?php echo htmlspecialchars($course['department_id'] ?? ''); ?>"
                                                    data-course-code="<?php echo htmlspecialchars($course['course_code'] ?? ''); ?>">
                                                <?php echo htmlspecialchars($course['course_name']); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_id" class="form-label fw-semibold">
                                    Registration Number (Student ID) <span class="text-danger">*</span>
                                </label>
                                <input type="text" class="form-control" id="student_id" name="student_id" 
                                       maxlength="50" required readonly>
                                <div class="form-text">Auto-generated based on course and academic year</div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label for="course_mode" class="form-label fw-semibold">Course Mode</label>
                                <select class="form-select" id="course_mode" name="course_mode">
                                    <option value="Full Time" selected>Full Time</option>
                                    <option value="Part Time">Part Time</option>
                                </select>
                            </div>
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_enroll_status" class="form-label fw-semibold">Enrollment Status</label>
                                <select class="form-select" id="student_enroll_status" name="student_enroll_status">
                                    <option value="Following" selected>Following</option>
                                    <option value="Dropout">Dropout</option>
                                    <option value="Completed">Completed</option>
                                    <option value="Long Absent">Long Absent</option>
                                </select>
                            </div>
                        </div>
                        
                        <hr class="my-4">
                        <h6 class="fw-bold mb-3">Personal Information</h6>
                        
                        <div class="row">
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_title" class="form-label fw-semibold">Title</label>
                                <select class="form-select" id="student_title" name="student_title">
                                    <option value="">Select</option>
                                    <option value="Mr.">Mr.</option>
                                    <option value="Mrs.">Mrs.</option>
                                    <option value="Miss">Miss</option>
                                    
                                </select>
                            </div>
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_gender" class="form-label fw-semibold">Gender</label>
                                <select class="form-select" id="student_gender" name="student_gender">
                                    <option value="">Select</option>
                                    <option value="Male">Male</option>
                                    <option value="Female">Female</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="student_fullname" class="form-label fw-semibold">
                                    Full Name <span class="text-danger">*</span>
                                </label>
                                <input type="text" class="form-control" id="student_fullname" name="student_fullname" 
                                       maxlength="255" required>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_ininame" class="form-label fw-semibold">Name with Initials</label>
                                <input type="text" class="form-control" id="student_ininame" name="student_ininame" 
                                       maxlength="255">
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="student_email" class="form-label fw-semibold">
                                    Email <span class="text-danger">*</span>
                                </label>
                                <input type="email" class="form-control" id="student_email" name="student_email" 
                                       maxlength="254" required>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_nic" class="form-label fw-semibold">
                                    NIC <span class="text-danger">*</span>
                                </label>
                                <input type="text" class="form-control" id="student_nic" name="student_nic" 
                                       maxlength="12" required>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-4 mb-3">
                                <label for="student_dob" class="form-label fw-semibold">Date of Birth</label>
                                <input type="date" class="form-control" id="student_dob" name="student_dob">
                            </div>
                            
                            <div class="col-md-4 mb-3">
                                <label for="student_phone" class="form-label fw-semibold">Phone</label>
                                <input type="tel" class="form-control" id="student_phone" name="student_phone" 
                                       pattern="[0-9]{9,10}">
                            </div>
                            
                            <div class="col-md-4 mb-3">
                                <label for="student_civil" class="form-label fw-semibold">Civil Status</label>
                                <select class="form-select" id="student_civil" name="student_civil">
                                    <option value="Single">Single</option>
                                    <option value="Married">Married</option>
                                    <option value="Divorced">Divorced</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="mb-3">
                            <label for="student_address" class="form-label fw-semibold">Address</label>
                            <textarea class="form-control" id="student_address" name="student_address" rows="2" maxlength="255"></textarea>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label for="student_zip" class="form-label fw-semibold">ZIP Code</label>
                                <input type="number" class="form-control" id="student_zip" name="student_zip" required>
                            </div>
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_provice" class="form-label fw-semibold">Province <span class="text-danger">*</span></label>
                                <select class="form-select" id="student_provice" name="student_provice" required>
                                    <option value="">Select Province</option>
                                    <option value="Western Province">Western Province</option>
                                    <option value="Central Province">Central Province</option>
                                    <option value="Southern Province">Southern Province</option>
                                    <option value="Northern Province">Northern Province</option>
                                    <option value="Eastern Province">Eastern Province</option>
                                    <option value="North Western Province">North Western Province</option>
                                    <option value="North Central Province">North Central Province</option>
                                    <option value="Uva Province">Uva Province</option>
                                    <option value="Sabaragamuwa Province">Sabaragamuwa Province</option>
                                </select>
                            </div>
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_district" class="form-label fw-semibold">District <span class="text-danger">*</span></label>
                                <select class="form-select" id="student_district" name="student_district" required>
                                    <option value="">Select District</option>
                                </select>
                            </div>
                            
                            <div class="col-md-3 mb-3">
                                <label for="student_divisions" class="form-label fw-semibold">Divisions</label>
                                <input type="text" class="form-control" id="student_divisions" name="student_divisions" maxlength="50" required>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="student_blood" class="form-label fw-semibold">Blood Group</label>
                                <select class="form-select" id="student_blood" name="student_blood">
                                    <option value="">Select</option>
                                    <option value="A+">A+</option>
                                    <option value="A-">A-</option>
                                    <option value="B+">B+</option>
                                    <option value="B-">B-</option>
                                    <option value="AB+">AB+</option>
                                    <option value="AB-">AB-</option>
                                    <option value="O+">O+</option>
                                    <option value="O-">O-</option>
                                </select>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_status" class="form-label fw-semibold">Status</label>
                                <select class="form-select" id="student_status" name="student_status">
                                    <option value="Active" selected>Active</option>
                                    <option value="Inactive">Inactive</option>
                                    <option value="Graduated">Graduated</option>
                                </select>
                            </div>
                        </div>
                        
                        <hr class="my-4">
                        <h6 class="fw-bold mb-3">Emergency Contact</h6>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="student_em_name" class="form-label fw-semibold">Emergency Contact Name</label>
                                <input type="text" class="form-control" id="student_em_name" name="student_em_name" maxlength="255">
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_em_relation" class="form-label fw-semibold">Relation</label>
                                <input type="text" class="form-control" id="student_em_relation" name="student_em_relation" maxlength="20">
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="student_em_address" class="form-label fw-semibold">Emergency Address</label>
                                <textarea class="form-control" id="student_em_address" name="student_em_address" rows="2" maxlength="255"></textarea>
                            </div>
                            
                            <div class="col-md-6 mb-3">
                                <label for="student_em_phone" class="form-label fw-semibold">Emergency Phone</label>
                                <input type="tel" class="form-control" id="student_em_phone" name="student_em_phone" 
                                       pattern="[0-9]{9,10}">
                            </div>
                        </div>
                        
                        <div class="d-flex gap-2 mt-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save me-1"></i>Create Student
                            </button>
                            <a href="<?php echo APP_URL; ?>/students" class="btn btn-outline-secondary">
                                <i class="fas fa-times me-1"></i>Cancel
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
// Sri Lanka Provinces and Districts mapping
const sriLankaDistricts = {
    'Western Province': ['Colombo', 'Gampaha', 'Kalutara'],
    'Central Province': ['Kandy', 'Matale', 'Nuwara Eliya'],
    'Southern Province': ['Galle', 'Matara', 'Hambantota'],
    'Northern Province': ['Jaffna', 'Kilinochchi', 'Mannar', 'Mullaitivu', 'Vavuniya'],
    'Eastern Province': ['Batticaloa', 'Ampara', 'Trincomalee'],
    'North Western Province': ['Kurunegala', 'Puttalam'],
    'North Central Province': ['Anuradhapura', 'Polonnaruwa'],
    'Uva Province': ['Badulla', 'Monaragala'],
    'Sabaragamuwa Province': ['Ratnapura', 'Kegalle']
};

// Function to load districts based on selected province
function loadDistricts(province) {
    const districtSelect = document.getElementById('student_district');
    districtSelect.innerHTML = '<option value="">Select District</option>';
    
    if (province && sriLankaDistricts[province]) {
        sriLankaDistricts[province].forEach(function(district) {
            const option = document.createElement('option');
            option.value = district;
            option.textContent = district;
            districtSelect.appendChild(option);
        });
    }
}

// Handle province change, department/course filtering, and auto-generate registration number
document.addEventListener('DOMContentLoaded', function() {
    const provinceSelect = document.getElementById('student_provice');
    if (provinceSelect) {
        provinceSelect.addEventListener('change', function() {
            loadDistricts(this.value);
        });
    }
    
    // Department and Course filtering
    const departmentSelect = document.getElementById('department_id');
    const courseSelect = document.getElementById('course_id');
    const academicYearSelect = document.getElementById('academic_year');
    const studentIdInput = document.getElementById('student_id');
    
    // Store all course options
    const allCourseOptions = [];
    if (courseSelect) {
        for (let i = 0; i < courseSelect.options.length; i++) {
            allCourseOptions.push(courseSelect.options[i]);
        }
    }
    
    // Filter courses based on selected department
    function filterCoursesByDepartment() {
        const selectedDepartmentId = departmentSelect ? departmentSelect.value : '';
        
        if (!courseSelect) return;
        
        // Clear current options
        courseSelect.innerHTML = '<option value="">Select Course</option>';
        studentIdInput.value = ''; // Clear registration number when department changes
        
        if (!selectedDepartmentId) {
            courseSelect.disabled = true;
            courseSelect.innerHTML = '<option value="">Select Department First</option>';
            return;
        }
        
        // Add courses that match the selected department
        let hasCourses = false;
        allCourseOptions.forEach(function(option) {
            if (option.value && option.getAttribute('data-department-id') === selectedDepartmentId) {
                courseSelect.appendChild(option.cloneNode(true));
                hasCourses = true;
            }
        });
        
        if (hasCourses) {
            courseSelect.disabled = false;
        } else {
            courseSelect.disabled = true;
            courseSelect.innerHTML = '<option value="">No courses available for this department</option>';
        }
    }
    
    // Auto-generate registration number when course and academic year are selected
    function generateRegistrationNumber() {
        const courseId = courseSelect.value;
        const academicYear = academicYearSelect.value;
        
        if (!courseId || !academicYear) {
            studentIdInput.value = '';
            return;
        }
        
        // Fetch last registration number via AJAX
        fetch('<?php echo APP_URL; ?>/students/get-last-reg-number?course_id=' + encodeURIComponent(courseId) + '&academic_year=' + encodeURIComponent(academicYear))
            .then(response => response.json())
            .then(data => {
                if (data.success && data.nextRegNumber) {
                    studentIdInput.value = data.nextRegNumber;
                } else {
                    // Generate first registration number if none exists
                    const courseOption = courseSelect.options[courseSelect.selectedIndex];
                    const courseCode = courseOption.getAttribute('data-course-code') || courseId.substring(0, 3).toUpperCase();
                    const year = academicYear.split('/')[0] || new Date().getFullYear();
                    studentIdInput.value = year + '_' + courseCode + '_001';
                }
            })
            .catch(error => {
                console.error('Error generating registration number:', error);
                // Fallback: generate basic format
                const courseOption = courseSelect.options[courseSelect.selectedIndex];
                const courseCode = courseOption.getAttribute('data-course-code') || courseId.substring(0, 3).toUpperCase();
                const year = academicYear.split('/')[0] || new Date().getFullYear();
                studentIdInput.value = year + '_' + courseCode + '_001';
            });
    }
    
    // Event listeners
    if (departmentSelect) {
        departmentSelect.addEventListener('change', function() {
            filterCoursesByDepartment();
            // Clear course selection and registration number when department changes
            if (courseSelect) {
                courseSelect.value = '';
            }
            studentIdInput.value = '';
        });
    }
    
    if (courseSelect && academicYearSelect && studentIdInput) {
        courseSelect.addEventListener('change', generateRegistrationNumber);
        academicYearSelect.addEventListener('change', generateRegistrationNumber);
    }
    
    // Excel Import Form - Department and Course filtering
    const importDepartmentSelect = document.getElementById('import_department_id');
    const importCourseSelect = document.getElementById('import_course_id');
    const allImportCourseOptions = [];
    
    if (importCourseSelect) {
        for (let i = 0; i < importCourseSelect.options.length; i++) {
            allImportCourseOptions.push(importCourseSelect.options[i]);
        }
    }
    
    function filterImportCoursesByDepartment() {
        const selectedDepartmentId = importDepartmentSelect ? importDepartmentSelect.value : '';
        
        if (!importCourseSelect) return;
        
        // Clear current options
        importCourseSelect.innerHTML = '<option value="">Select Course</option>';
        
        if (!selectedDepartmentId) {
            importCourseSelect.disabled = true;
            importCourseSelect.innerHTML = '<option value="">Select Department First</option>';
            return;
        }
        
        // Add courses that match the selected department
        let hasCourses = false;
        allImportCourseOptions.forEach(function(option) {
            if (option.value && option.getAttribute('data-department-id') === selectedDepartmentId) {
                importCourseSelect.appendChild(option.cloneNode(true));
                hasCourses = true;
            }
        });
        
        if (hasCourses) {
            importCourseSelect.disabled = false;
        } else {
            importCourseSelect.disabled = true;
            importCourseSelect.innerHTML = '<option value="">No courses available for this department</option>';
        }
    }
    
    if (importDepartmentSelect) {
        importDepartmentSelect.addEventListener('change', filterImportCoursesByDepartment);
    }
    
    // Form validation: Ensure Full Name and NIC are required when enrollment is being created
    const createForm = document.getElementById('createStudentForm');
    const fullNameInput = document.getElementById('student_fullname');
    const nicInput = document.getElementById('student_nic');
    
    if (createForm && departmentSelect && courseSelect && academicYearSelect && fullNameInput && nicInput) {
        createForm.addEventListener('submit', function(e) {
            const hasDepartment = departmentSelect.value !== '';
            const hasCourse = courseSelect.value !== '';
            const hasAcademicYear = academicYearSelect.value !== '';
            
            // If enrollment fields are filled, Full Name and NIC must be filled
            if (hasDepartment && hasCourse && hasAcademicYear) {
                if (!fullNameInput.value.trim()) {
                    e.preventDefault();
                    alert('Full Name is required when creating enrollment.');
                    fullNameInput.focus();
                    return false;
                }
                
                if (!nicInput.value.trim()) {
                    e.preventDefault();
                    alert('NIC is required when creating enrollment.');
                    nicInput.focus();
                    return false;
                }
            }
        });
    }
});
</script>

