-- SLGTI Device / Laptop Asset Management Module
-- Run once on the target database (also auto-created via DeviceModel::ensureTables()).

CREATE TABLE IF NOT EXISTS `devices` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
    `asset_id` VARCHAR(50) NOT NULL,
    `asset_tag_no` VARCHAR(50) DEFAULT NULL,
    `device_type` ENUM('Laptop','Desktop','Tablet','Other') NOT NULL DEFAULT 'Laptop',
    `brand` VARCHAR(100) DEFAULT NULL,
    `model` VARCHAR(100) DEFAULT NULL,
    `serial_number` VARCHAR(100) DEFAULT NULL,
    `product_number` VARCHAR(100) DEFAULT NULL,
    `service_tag` VARCHAR(100) DEFAULT NULL,
    `computer_name` VARCHAR(100) DEFAULT NULL,
    `processor` VARCHAR(150) DEFAULT NULL,
    `ram` VARCHAR(50) DEFAULT NULL,
    `storage_type` VARCHAR(50) DEFAULT NULL,
    `storage_capacity` VARCHAR(50) DEFAULT NULL,
    `display_size` VARCHAR(30) DEFAULT NULL,
    `operating_system` VARCHAR(100) DEFAULT NULL,
    `purchase_date` DATE DEFAULT NULL,
    `supplier` VARCHAR(255) DEFAULT NULL,
    `purchase_cost` DECIMAL(12,2) DEFAULT NULL,
    `warranty_expiry` DATE DEFAULT NULL,
    `lan_mac_address` VARCHAR(50) DEFAULT NULL,
    `wifi_mac_address` VARCHAR(50) DEFAULT NULL,
    `charger_serial_no` VARCHAR(100) DEFAULT NULL,
    `battery_serial_no` VARCHAR(100) DEFAULT NULL,
    `assigned_employee_id` VARCHAR(20) DEFAULT NULL COMMENT 'staff.staff_id',
    `status` ENUM('available','assigned','under_maintenance','damaged','lost','returned','retired','disposed') NOT NULL DEFAULT 'available',
    `windows_activated` TINYINT(1) NOT NULL DEFAULT 0,
    `ms_office_activated` TINYINT(1) NOT NULL DEFAULT 0,
    `bitlocker_enabled` TINYINT(1) NOT NULL DEFAULT 0,
    `antivirus_installed` TINYINT(1) NOT NULL DEFAULT 0,
    `cond_lcd_screen` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `cond_keyboard` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `cond_touchpad` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `cond_battery` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `cond_ports` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `cond_charger` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `cond_outer_body` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `condition_remarks` TEXT DEFAULT NULL,
    `qr_token` VARCHAR(64) NOT NULL,
    `qr_generated_at` DATETIME DEFAULT NULL,
    `remarks` TEXT DEFAULT NULL,
    `created_by` INT DEFAULT NULL,
    `updated_by` INT DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_devices_uuid` (`uuid`),
    UNIQUE KEY `uq_devices_asset_id` (`asset_id`),
    UNIQUE KEY `uq_devices_qr_token` (`qr_token`),
    KEY `idx_devices_status` (`status`),
    KEY `idx_devices_type` (`device_type`),
    KEY `idx_devices_assigned` (`assigned_employee_id`),
    KEY `idx_devices_warranty` (`warranty_expiry`),
    KEY `idx_devices_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `device_accessories` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `device_id` INT UNSIGNED NOT NULL,
    `accessory_type` ENUM('Laptop','Charger','Carry Bag','Wireless Mouse','Keyboard','Docking Station','HDMI Cable','Adapter','Other') NOT NULL,
    `serial_number` VARCHAR(100) DEFAULT NULL,
    `status` ENUM('Good','Fair','Damaged','Missing') NOT NULL DEFAULT 'Good',
    `remarks` VARCHAR(255) DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_device_accessories_device` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `device_assignments` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `device_id` INT UNSIGNED NOT NULL,
    `employee_id` VARCHAR(20) NOT NULL COMMENT 'staff.staff_id',
    `issue_date` DATE DEFAULT NULL,
    `return_date` DATE DEFAULT NULL,
    `issued_by` INT DEFAULT NULL,
    `returned_by` INT DEFAULT NULL,
    `remarks` TEXT DEFAULT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_device_assignments_device` (`device_id`),
    KEY `idx_device_assignments_employee` (`employee_id`),
    KEY `idx_device_assignments_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `device_condition_history` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `device_id` INT UNSIGNED NOT NULL,
    `lcd_screen` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `keyboard` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `touchpad` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `battery` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `ports` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `charger` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `outer_body` ENUM('Good','Fair','Damaged') DEFAULT NULL,
    `remarks` TEXT DEFAULT NULL,
    `recorded_by` INT DEFAULT NULL,
    `recorded_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_device_condition_device` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `device_audit_logs` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `device_id` INT UNSIGNED DEFAULT NULL,
    `user_id` INT DEFAULT NULL,
    `action` VARCHAR(80) NOT NULL,
    `old_values` JSON DEFAULT NULL,
    `new_values` JSON DEFAULT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `user_agent` VARCHAR(255) DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_device_audit_device` (`device_id`),
    KEY `idx_device_audit_user` (`user_id`),
    KEY `idx_device_audit_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
