<?php
/** Common G.C.E. A/L subject titles (English) — pick-list for three subject slots. */
declare(strict_types=1);

return [
    'Combined Mathematics',
    'Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Agricultural Science',
    'Science for Technology',
    'Economics',
    'Business Studies',
    'Accounting',
    'Business Statistics',
    'Information & Communication Technology',
    'Geography',
    'History',
    'Civic Education',
    'Political Science',
    'Logic & Scientific Method',
    'Sinhala',
    'Tamil',
    'English',
    'English Literature',
    'French',
    'German',
    'Hindi',
    'Japanese',
    'Arabic',
    'Chinese',
    'Media & Communication Studies',
    'Art',
    'Music',
    'Dancing',
    'Drama & Theatre',
    'Engineering Technology',
    'Bio-systems Technology',
    'Other (see A/L certificate)',
];
