<?php
// Database Configuration
// This file is auto-generated by install.php

if (!defined('DB_HOST')) {
    define('DB_HOST', 'localhost');
    define('DB_USER', 'root');
    define('DB_PASS', '1234');
    define('DB_NAME', 'sisslgti');
    define('DB_CHARSET', 'utf8mb4');
}

// Application Configuration
if (!defined('APP_NAME')) {
    define('APP_NAME', 'SLGTI SIS');
    define('APP_URL', 'http://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['SCRIPT_NAME']));
}

// BASE_PATH is defined in index.php
// If not defined, set it here (shouldn't happen)
if (!defined('BASE_PATH')) {
    define('BASE_PATH', dirname(__DIR__));
}
