<?php
// Database Configuration
// This file is auto-generated by install.php

if (!defined('DB_HOST')) {
    define('DB_HOST', 'localhost');
    define('DB_USER', 'root');
    define('DB_PASS', '1234');
    define('DB_NAME', 'sisslgti');
    define('DB_CHARSET', 'utf8mb4');
}

// Application Configuration
if (!defined('APP_NAME')) {
    define('APP_NAME', 'SLGTI SIS');
    // Detect HTTPS automatically
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || 
                (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443) ||
                (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
                ? 'https://' : 'http://';
    // Get base path and normalize it (remove trailing slash, handle root case)
    $basePath = dirname($_SERVER['SCRIPT_NAME']);
    $basePath = rtrim($basePath, '/\\'); // Remove trailing slashes
    // If basePath is empty or just a slash, set it to empty string
    if ($basePath === '/' || $basePath === '\\' || empty($basePath)) {
        $basePath = '';
    }
    define('APP_URL', $protocol . $_SERVER['HTTP_HOST'] . $basePath);
}

// BASE_PATH is defined in index.php
// If not defined, set it here (shouldn't happen)
if (!defined('BASE_PATH')) {
    define('BASE_PATH', dirname(__DIR__));
}
