<?php
/**
 * Application Routes
 */

return [
    '' => 'HomeController@index',
    'home' => 'HomeController@index',
    'login' => 'AuthController@login',
    'logout' => 'AuthController@logout',
    
    // Admin Security Routes
    'admin/users' => 'AdminController@users',
    'admin/locked-accounts' => 'AdminController@lockedAccounts',
    'admin/unlock-account' => 'AdminController@unlockAccount',
    'admin/reset-password' => 'AdminController@resetPassword',
    'admin/activity-logs' => 'AdminController@activityLogs',
    'admin/backup-db' => 'AdminController@backupDb',
    'profile' => 'ProfileController@index',
    'profile/update' => 'ProfileController@update',
    'dashboard' => 'DashboardController@index',
    // HOD Dashboard Route
    'hod/dashboard' => 'HODDashboardController@index',
    // Student Portal Routes
    'student/dashboard' => 'StudentDashboardController@index',
    'student/payments' => 'StudentDashboardController@payments',
    'student/profile' => 'StudentController@showStudentProfile',
    'student/profile/edit' => 'StudentController@editStudentProfile',
    'student/change-password' => 'StudentController@changeStudentPassword',
    'student/accept-conduct' => 'StudentController@acceptConduct',
    'student/attendance' => 'StudentAttendanceController@index',
    'students' => 'StudentController@index',
    'students/view' => 'StudentController@show',
    'students/create' => 'StudentController@create',
    'students/edit' => 'StudentController@edit',
    'students/delete' => 'StudentController@delete',
    'students/reset-password' => 'StudentController@resetPassword',
    'students/get-last-reg-number' => 'StudentController@getLastRegNumber',
    'students/import-excel' => 'StudentController@importExcel',
    'students/download-sample-excel' => 'StudentController@downloadSampleExcel',
    'students/import-images' => 'StudentController@importImages',
    'students/upload-images' => 'StudentController@uploadImages',
    'students/export-excel' => 'StudentController@exportExcel',
    // Student ID card (ADM only)
    'students/id-card-select' => 'StudentController@idCardSelect',
    'students/id-card' => 'StudentController@idCard',
    'students/id-card-download' => 'StudentController@idCardDownload',
    'students/id-card-download-zip' => 'StudentController@idCardDownloadZip',
    // Alias: download JPGs (front/back) as ZIP
    'students/id-card-download-jpg' => 'StudentController@idCardDownloadZip',
    'staff' => 'StaffController@index',
    'staff/create' => 'StaffController@create',
    'staff/edit' => 'StaffController@edit',
    'staff/delete' => 'StaffController@delete',
    'staff-roles' => 'StaffRoleController@index',
    'staff-roles/create' => 'StaffRoleController@create',
    'staff-roles/edit' => 'StaffRoleController@edit',
    'staff-roles/delete' => 'StaffRoleController@delete',
    'departments' => 'DepartmentController@index',
    'departments/create' => 'DepartmentController@create',
    'departments/edit' => 'DepartmentController@edit',
    'departments/delete' => 'DepartmentController@delete',
    'courses' => 'CourseController@index',
    'courses/get-by-department' => 'CourseController@getByDepartment',
    'courses/create' => 'CourseController@create',
    'courses/edit' => 'CourseController@edit',
    'courses/new-version' => 'CourseController@newVersion',
    'courses/remove-version' => 'CourseController@removeVersion',
    'courses/delete' => 'CourseController@delete',
    'modules' => 'ModuleController@index',
    'modules/view' => 'ModuleController@show',
    'modules/create' => 'ModuleController@create',
    'modules/import-excel' => 'ModuleController@importExcel',
    'modules/download-sample-excel' => 'ModuleController@downloadSampleExcel',
    'modules/edit' => 'ModuleController@edit',
    'modules/delete' => 'ModuleController@delete',
    'attendance' => 'AttendanceController@index',
    'attendance/bulk-update' => 'AttendanceController@bulkUpdate',
    'attendance/report' => 'AttendanceController@report',
    'attendance/range-summary' => 'AttendanceController@rangeSummaryReport',
    'attendance/export-range-summary' => 'AttendanceController@exportRangeSummaryReport',
    'attendance/export-report' => 'AttendanceController@exportReport',
    'attendance/month-sheet' => 'AttendanceController@monthSheet',
    'attendance/export-month-sheet' => 'AttendanceController@exportMonthSheet',
    'attendance/lock-month' => 'AttendanceController@lockMonth',
    'attendance/unlock-month' => 'AttendanceController@unlockMonth',
    'attendance/staff' => 'AttendanceController@staffAttendance',
    'attendance/staff-device' => 'AttendanceController@staffDeviceDashboard',
    'attendance/staff-device/list' => 'AttendanceController@staffDeviceList',
    'attendance/staff-device/daily' => 'AttendanceController@staffDeviceDaily',
    'attendance/staff-device/month' => 'AttendanceController@staffDeviceMonth',
    'attendance/staff-device/sync' => 'AttendanceController@staffDeviceSync',
    'attendance/sync-hikvision' => 'AttendanceController@syncHikvision',
    'attendance/test-hikvision' => 'AttendanceController@testHikvision',
    'attendance/hikvision-report' => 'AttendanceController@getHikvisionReport',
    'attendance/machine' => 'AttendanceController@machineAttendance',
    'attendance/export-machine' => 'AttendanceController@exportMachineAttendance',
    'attendance/get-groups-by-course-and-year' => 'AttendanceController@getGroupsByCourseAndYear',
    'payments' => 'PaymentController@index',
    'payments/create' => 'PaymentController@create',
    'payments/receipt' => 'PaymentController@receipt',
    'payments/edit' => 'PaymentController@edit',
    'payments/delete' => 'PaymentController@delete',
    'payment-types' => 'PaymentTypeController@index',
    'payment-types/create' => 'PaymentTypeController@create',
    'payment-types/edit' => 'PaymentTypeController@edit',
    'payment-types/delete' => 'PaymentTypeController@delete',
    'hostels' => 'HostelController@index',
    'hostels/create' => 'HostelController@create',
    'hostels/edit' => 'HostelController@edit',
    'hostels/delete' => 'HostelController@delete',
    'rooms' => 'RoomController@index',
    'rooms/create' => 'RoomController@create',
    'rooms/edit' => 'RoomController@edit',
    'rooms/delete' => 'RoomController@delete',
    'rooms/get-blocks' => 'RoomController@getBlocks',
    'room-allocations' => 'RoomAllocationController@index',
    'room-allocations/create' => 'RoomAllocationController@create',
    'room-allocations/edit' => 'RoomAllocationController@edit',
    'room-allocations/delete' => 'RoomAllocationController@delete',
    'room-allocations/deallocate' => 'RoomAllocationController@deallocate',
    'room-allocations/get-available-rooms' => 'RoomAllocationController@getAvailableRooms',
    'room-allocations/export-excel' => 'RoomAllocationController@exportExcel',
    // On-Peak/Off-Peak Requests
    'on-peak-requests' => 'OnPeakRequestController@index',
    'on-peak-requests/create' => 'OnPeakRequestController@create',
    'on-peak-requests/cancel' => 'OnPeakRequestController@cancel',
    'on-peak-requests/view' => 'OnPeakRequestController@show',
    'on-peak-requests/hod-approval' => 'OnPeakRequestController@hodApproval',
    'on-peak-requests/hod-approve' => 'OnPeakRequestController@hodApprove',
    'on-peak-requests/final-approval' => 'OnPeakRequestController@finalApproval',
    'on-peak-requests/final-approve' => 'OnPeakRequestController@finalApprove',
    // Bus Season Requests
    'bus-season-requests' => 'BusSeasonRequestController@index',
    'bus-season-requests/create' => 'BusSeasonRequestController@create',
    'bus-season-requests/view' => 'BusSeasonRequestController@show',
    'bus-season-requests/hod-approval' => 'BusSeasonRequestController@hodApproval',
    'bus-season-requests/hod-approve' => 'BusSeasonRequestController@hodApprove',
    'bus-season-requests/second-approval' => 'BusSeasonRequestController@secondApproval',
    'bus-season-requests/second-approve' => 'BusSeasonRequestController@secondApprove',
    'bus-season-requests/sao-process' => 'BusSeasonRequestController@saoProcess',
    'bus-season-requests/sao-process-save' => 'BusSeasonRequestController@saoProcessSave',
    'bus-season-requests/update-route' => 'BusSeasonRequestController@updateRoute',
    'bus-season-requests/sao-create-request' => 'BusSeasonRequestController@saoCreateRequest',
    'bus-season-requests/update-payment-status' => 'BusSeasonRequestController@updatePaymentStatus',
    'bus-season-requests/edit-payment' => 'BusSeasonRequestController@editPayment',
    'bus-season-requests/delete-payment' => 'BusSeasonRequestController@deletePayment',
    'bus-season-requests/bulk-update-status' => 'BusSeasonRequestController@bulkUpdateStatus',
    'bus-season-requests/export-payments' => 'BusSeasonRequestController@exportPaymentsExcel',
    'bus-season-requests/payment-collections' => 'BusSeasonRequestController@paymentCollections',

    // Deleted students (ADM-only view handled in StudentController)
    'admin/deleted-students' => 'StudentController@deletedStudents',
    // Circuit Program
    'circuit-program' => 'CircuitProgramController@index',
    'circuit-program/create' => 'CircuitProgramController@create',
    'circuit-program/view' => 'CircuitProgramController@show',
    'circuit-program/approval' => 'CircuitProgramController@approval',
    'circuit-program/approve' => 'CircuitProgramController@approve',
    'circuit-program/delete' => 'CircuitProgramController@delete',
    // Groups
    'groups' => 'GroupController@index',
    'groups/create' => 'GroupController@create',
    'groups/show' => 'GroupController@show',
    'groups/edit' => 'GroupController@edit',
    'groups/delete' => 'GroupController@delete',
    'groups/add-students' => 'GroupController@addStudents',
    'groups/remove-student' => 'GroupController@removeStudent',
    'groups/get-courses-by-department' => 'GroupController@getCoursesByDepartment',
    'groups/get-available-students' => 'GroupController@getAvailableStudents',
    // Staff module enrollment (HOD)
    'hod/staff-module-enroll' => 'StaffModuleEnrollmentController@create',
    'hod/get-modules-by-course' => 'StaffModuleEnrollmentController@getModulesByCourse',
    // Instructor diary (IN1/IN2/IN3/LE1/LE2/SLE/HOD)
    'instructor-diary' => 'InstructorDiaryController@index',
    'instructor-diary/create' => 'InstructorDiaryController@create',
    'hod/instructor-diary' => 'InstructorDiaryController@hodReport',
    'hod/instructor-diary/export' => 'InstructorDiaryController@hodReportExport',
    // Inventory management
    'inventory' => 'InventoryController@dashboard',
    'inventory/items' => 'InventoryController@itemsIndex',
    'inventory/items/create' => 'InventoryController@itemsCreate',
    'inventory/items/edit' => 'InventoryController@itemsEdit',
    'inventory/items/delete' => 'InventoryController@itemsDelete',
    'inventory/stock-in' => 'InventoryController@stockIn',
    'inventory/stock-out' => 'InventoryController@stockOut',
    'inventory/transfer' => 'InventoryController@transfer',
    'inventory/log' => 'InventoryController@log',

    // Exams (EXAM / ADM)
    'exams' => 'ExamController@index',
    'exams/create' => 'ExamController@create',
    'exams/store' => 'ExamController@store',
    'exams/edit' => 'ExamController@edit',
    'exams/update' => 'ExamController@update',
    'exams/delete' => 'ExamController@deleteExam',
    'exams/ajax/modules' => 'ExamController@ajaxModules',
    'exams/ajax/groups' => 'ExamController@ajaxGroups',
    'exams/ajax/students' => 'ExamController@ajaxStudents',
    'exams/admission-select' => 'ExamController@admissionSelect',
    'marks/enter' => 'MarkController@enterMarks',
    'marks/save' => 'MarkController@saveMarks',
    'print/attendance-sheet' => 'PrintController@attendanceSheet',
    'print/first-mark-sheet' => 'PrintController@firstMarkSheet',
    'print/second-mark-sheet' => 'PrintController@secondMarkSheet',
    'print/admission-card' => 'PrintController@admissionCard',
    'print/admission-cards-bulk' => 'PrintController@admissionCardsBulk',
    'print/admission-cards-selected' => 'PrintController@admissionCardsSelected',

    // Public student applications — no login (Level 05 uses /level05application/ procedural wizard folder)
    'level04application' => 'StudentApplicationController@level04',
    'student-application/api/check-application' => 'StudentApplicationController@apiCheckApplication',
    'student-application/api/insert-draft' => 'StudentApplicationController@apiInsertDraft',
    'student-application/api/save-progress' => 'StudentApplicationController@apiSaveProgress',
    'student-application/api/departments' => 'StudentApplicationController@apiDepartments',
    'student-application/api/courses' => 'StudentApplicationController@apiCourses',
    'student-applications' => 'StudentApplicationController@adminIndex',
    'student-applications/ajax-table' => 'StudentApplicationController@adminAjaxTable',
    'student-applications/view' => 'StudentApplicationController@adminView',
    'student-applications/edit' => 'StudentApplicationController@adminEdit',
    'student-applications/approve' => 'StudentApplicationController@adminApprove',
    'student-applications/reject' => 'StudentApplicationController@adminReject',
    'student-applications/download-document' => 'StudentApplicationController@adminDownloadDocument',
    'student-applications/export-data' => 'StudentApplicationController@adminExportApplicationData',
    'student-applications/export-pdf' => 'StudentApplicationController@adminExportApplicationPdf',
    'student-applications/export-excel' => 'StudentApplicationController@adminExportExcel',
    'student-applications/delete' => 'StudentApplicationController@adminDelete',
];

