<?php
/**
 * Application Routes
 */

return [
    '' => 'HomeController@index',
    'home' => 'HomeController@index',
    'login' => 'AuthController@login',
    'logout' => 'AuthController@logout',
    
    // Admin Security Routes
    'admin/users' => 'AdminController@users',
    'admin/locked-accounts' => 'AdminController@lockedAccounts',
    'admin/unlock-account' => 'AdminController@unlockAccount',
    'admin/reset-password' => 'AdminController@resetPassword',
    'admin/activity-logs' => 'AdminController@activityLogs',
    'profile' => 'ProfileController@index',
    'profile/update' => 'ProfileController@update',
    'dashboard' => 'DashboardController@index',
    // HOD Dashboard Route
    'hod/dashboard' => 'HODDashboardController@index',
    // Student Portal Routes
    'student/dashboard' => 'StudentDashboardController@index',
    'student/profile' => 'StudentController@showStudentProfile',
    'student/attendance' => 'StudentAttendanceController@index',
    'students' => 'StudentController@index',
    'students/view' => 'StudentController@show',
    'students/create' => 'StudentController@create',
    'students/edit' => 'StudentController@edit',
    'students/delete' => 'StudentController@delete',
    'students/reset-password' => 'StudentController@resetPassword',
    'students/get-last-reg-number' => 'StudentController@getLastRegNumber',
    'students/import-excel' => 'StudentController@importExcel',
    'students/download-sample-excel' => 'StudentController@downloadSampleExcel',
    'students/import-images' => 'StudentController@importImages',
    'students/upload-images' => 'StudentController@uploadImages',
    'students/export-excel' => 'StudentController@exportExcel',
    'staff' => 'StaffController@index',
    'staff/create' => 'StaffController@create',
    'staff/edit' => 'StaffController@edit',
    'staff/delete' => 'StaffController@delete',
    'staff-roles' => 'StaffRoleController@index',
    'staff-roles/create' => 'StaffRoleController@create',
    'staff-roles/edit' => 'StaffRoleController@edit',
    'staff-roles/delete' => 'StaffRoleController@delete',
    'departments' => 'DepartmentController@index',
    'departments/create' => 'DepartmentController@create',
    'departments/edit' => 'DepartmentController@edit',
    'departments/delete' => 'DepartmentController@delete',
    'courses' => 'CourseController@index',
    'courses/get-by-department' => 'CourseController@getByDepartment',
    'courses/create' => 'CourseController@create',
    'courses/edit' => 'CourseController@edit',
    'courses/delete' => 'CourseController@delete',
    'attendance' => 'AttendanceController@index',
    'attendance/bulk-update' => 'AttendanceController@bulkUpdate',
    'attendance/report' => 'AttendanceController@report',
    'attendance/export-report' => 'AttendanceController@exportReport',
    'attendance/lock-month' => 'AttendanceController@lockMonth',
    'attendance/unlock-month' => 'AttendanceController@unlockMonth',
    'attendance/staff' => 'AttendanceController@staffAttendance',
    'attendance/sync-hikvision' => 'AttendanceController@syncHikvision',
    'attendance/test-hikvision' => 'AttendanceController@testHikvision',
    'attendance/hikvision-report' => 'AttendanceController@getHikvisionReport',
    'attendance/machine' => 'AttendanceController@machineAttendance',
    'attendance/export-machine' => 'AttendanceController@exportMachineAttendance',
    'payments' => 'PaymentController@index',
    'payments/create' => 'PaymentController@create',
    'payments/edit' => 'PaymentController@edit',
    'payments/delete' => 'PaymentController@delete',
    'hostels' => 'HostelController@index',
    'hostels/create' => 'HostelController@create',
    'hostels/edit' => 'HostelController@edit',
    'hostels/delete' => 'HostelController@delete',
    'rooms' => 'RoomController@index',
    'rooms/create' => 'RoomController@create',
    'rooms/edit' => 'RoomController@edit',
    'rooms/delete' => 'RoomController@delete',
    'rooms/get-blocks' => 'RoomController@getBlocks',
    'room-allocations' => 'RoomAllocationController@index',
    'room-allocations/create' => 'RoomAllocationController@create',
    'room-allocations/edit' => 'RoomAllocationController@edit',
    'room-allocations/delete' => 'RoomAllocationController@delete',
    'room-allocations/deallocate' => 'RoomAllocationController@deallocate',
    'room-allocations/get-available-rooms' => 'RoomAllocationController@getAvailableRooms',
    // On-Peak/Off-Peak Requests
    'on-peak-requests' => 'OnPeakRequestController@index',
    'on-peak-requests/create' => 'OnPeakRequestController@create',
    'on-peak-requests/cancel' => 'OnPeakRequestController@cancel',
    'on-peak-requests/view' => 'OnPeakRequestController@show',
    'on-peak-requests/hod-approval' => 'OnPeakRequestController@hodApproval',
    'on-peak-requests/hod-approve' => 'OnPeakRequestController@hodApprove',
    'on-peak-requests/final-approval' => 'OnPeakRequestController@finalApproval',
    'on-peak-requests/final-approve' => 'OnPeakRequestController@finalApprove',
    // Bus Season Requests
    'bus-season-requests' => 'BusSeasonRequestController@index',
    'bus-season-requests/create' => 'BusSeasonRequestController@create',
    'bus-season-requests/view' => 'BusSeasonRequestController@show',
    'bus-season-requests/hod-approval' => 'BusSeasonRequestController@hodApproval',
    'bus-season-requests/hod-approve' => 'BusSeasonRequestController@hodApprove',
    'bus-season-requests/second-approval' => 'BusSeasonRequestController@secondApproval',
    'bus-season-requests/second-approve' => 'BusSeasonRequestController@secondApprove',
    'bus-season-requests/sao-process' => 'BusSeasonRequestController@saoProcess',
    'bus-season-requests/sao-process-save' => 'BusSeasonRequestController@saoProcessSave',
    'bus-season-requests/payment-collections' => 'BusSeasonRequestController@paymentCollections',
    // Circuit Program
    'circuit-program' => 'CircuitProgramController@index',
    'circuit-program/create' => 'CircuitProgramController@create',
    'circuit-program/view' => 'CircuitProgramController@show',
    'circuit-program/approval' => 'CircuitProgramController@approval',
    'circuit-program/approve' => 'CircuitProgramController@approve',
    'circuit-program/delete' => 'CircuitProgramController@delete',
    // Groups
    'groups' => 'GroupController@index',
    'groups/create' => 'GroupController@create',
    'groups/show' => 'GroupController@show',
    'groups/edit' => 'GroupController@edit',
    'groups/delete' => 'GroupController@delete',
    'groups/add-students' => 'GroupController@addStudents',
    'groups/remove-student' => 'GroupController@removeStudent',
    'groups/get-courses-by-department' => 'GroupController@getCoursesByDepartment',
    'groups/get-available-students' => 'GroupController@getAvailableStudents',
    // Group Timetable
    'group-timetable/index' => 'GroupTimetableController@index',
    'group-timetable/create' => 'GroupTimetableController@create',
    'group-timetable/edit' => 'GroupTimetableController@edit',
    'group-timetable/delete' => 'GroupTimetableController@delete',
    'group-timetable/student-view' => 'GroupTimetableController@studentView',
];

